title: webhaus
email: tonywok@gmail.com
author: Tony Schneider
description: >
  Some things I decided to jot down.
  Not necessarily now, but then.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  tonywok
rss: RSS

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock

minima:
  date_format: "%b %-d, %Y"