title: tonywok
email: tonywok@gmail.com
description: >
  You've stumbled upon a collection of thoughts I thought important enough to write down at some point or another.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: tonywok
github_username:  tonywok


# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-paginate-v2
exclude:
  - Gemfile
  - Gemfile.lock
